services:
  interview-api:
    build: apps/interviewing-service/
    image: highload_systems_proj-interviewing-service:latest
    environment:
      APPLICATION_PROFILE: interview-web

  interviewer-api:
    build: apps/interviewing-service/
    image: highload_systems_proj-interviewing-service:latest
    environment:
      APPLICATION_PROFILE: interviewer-web

  interview-result-api:
    build: apps/interviewing-service/
    image: highload_systems_proj-interviewing-service:latest
    environment:
      APPLICATION_PROFILE: interview-result-web

  candidate-api:
    build: apps/interviewing-service/
    image: highload_systems_proj-interviewing-service:latest
    environment:
      APPLICATION_PROFILE: candidate-web

  feedback-api:
    build: apps/interviewing-service/
    image: highload_systems_proj-interviewing-service:latest
    environment:
      APPLICATION_PROFILE: feedback-web

  worker:
    build: apps/interviewing-service/
    image: highload_systems_proj-interviewing-service:latest
    environment:
      APPLICATION_PROFILE: worker

  authorizator:
    build: apps/authorizator
    image: highload_systems_proj-authorizator:latest

  api-gateway:
    build: apps/api-gateway
    image: highload_systems_proj-api-gateway:latest
    ports:
      - "8080:8765"
    healthcheck:
      test: curl --fail http://api-gateway:8765/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  config-server:
    build: service-discovery/config-server
    image: highload_systems_proj-config-server:latest
    ports:
      - "8888:8888"
    environment:
      PATH_TO_CONFIG_DIR: /app/service-discovery/config
      PROFILE: native
    healthcheck:
      test: curl --fail http://config-server:8888/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  eureka-server:
    build: service-discovery/eureka-server
    image: highload_systems_proj-eureka-server:latest
    ports:
      - "8761:8761"
    healthcheck:
      test: curl --fail http://eureka-server:8761/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  interviewing-service-postgres:
    build: ./pg
    image: highload_systems_proj-interviewing-service-postgres:latest
    ports:
      - '5252:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interviewing-service-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

