services:
  interviewing-service:
    build: ./
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USERNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres

  postgres:
    build: ./pg
    ports:
      - '5252:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 5

