services:
  file-manager:
    build: apps/file-manager
    image: kyoto67/highload/file-manager:latest
    ports:
      - "8887:8080"

  interviews:
    build: apps/interviewing-service/interviews
    image: kyoto67/highload/interviewing-service/interviews:latest

  interviewers:
    build: apps/interviewing-service/interviewers
    image: kyoto67/highload/interviewing-service/interviewers:latest

  interview-results:
    build: apps/interviewing-service/interview-results
    image: kyoto67/highload/interviewing-service/interview-results:latest

  candidates:
    build: apps/interviewing-service/candidates
    image: kyoto67/highload/interviewing-service/candidates:latest

  feedbacks:
    build: apps/interviewing-service/feedbacks
    image: kyoto67/highload/interviewing-service/feedbacks:latest

  authorizator:
    build: apps/authorizator
    image: kyoto67/highload/authorizator:latest
    ports:
      - "8877:8080"

  passport:
    build: apps/passport
    image: kyoto67/highload/passport:latest
    ports:
      - "81:81"
    healthcheck:
      test: curl --fail http://passport:81/ping || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  api-gateway:
    build: apps/api-gateway
    image: kyoto67/highload/api-gateway:latest
    ports:
      - "8080:8765"
    healthcheck:
      test: curl --fail http://api-gateway:8765/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  config-server:
    build: service-discovery/config-server
    image: kyoto67/highload/config-server:latest
    ports:
      - "8888:8888"
    environment:
      PATH_TO_CONFIG_DIR: /app/service-discovery/config
      PROFILE: native
    healthcheck:
      test: curl --fail http://config-server:8888/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  eureka-server:
    build: service-discovery/eureka-server
    image: kyoto67/highload/eureka-server:latest
    ports:
      - "8761:8761"
    healthcheck:
      test: curl --fail http://eureka-server:8761/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  interviews-postgres:
    build: ./pg
    image: kyoto67/highload/interviews-postgres:latest
    ports:
      - '5252:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interviews-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  interviewers-postgres:
    build: ./pg
    image: kyoto67/highload/interviewers-postgres:latest
    ports:
      - '5253:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interviewers-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  interview-results-postgres:
    build: ./pg
    image: kyoto67/highload/interview-results-postgres:latest
    ports:
      - '5254:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interview-results-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  feedbacks-postgres:
    build: ./pg
    image: kyoto67/highload/feedbacks-postgres:latest
    ports:
      - '5255:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=feedbacks-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  candidates-postgres:
    build: ./pg
    image: kyoto67/highload/candidates-postgres:latest
    ports:
      - '5256:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=candidates-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  passport-postgres:
    build: ./pg
    image: kyoto67/highload/passport-postgres:latest
    ports:
      - '5251:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=passport-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  api-gateway-postgres:
    build: ./pg
    image: kyoto67/highload/api-gateway-postgres:latest
    ports:
      - '5353:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=api-gateway-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50
