services:
  file-manager:
    build: apps/file-manager
    image: kyoto67/highload/file-manager:latest
    ports:
      - "8887:8080"

  interviews:
    build: apps/interviewing-service/interviews
    image: kyoto67/highload/interviewing-service/interviews:latest

  interviewers:
    build: apps/interviewing-service/interviewers
    image: kyoto67/highload/interviewing-service/interviewers:latest

  interview-results:
    build: apps/interviewing-service/interview-results
    image: kyoto67/highload/interviewing-service/interview-results:latest

  candidates:
    build: apps/interviewing-service/candidates
    image: kyoto67/highload/interviewing-service/candidates:latest

  feedbacks:
    build: apps/interviewing-service/feedbacks
    image: kyoto67/highload/interviewing-service/feedbacks:latest

  authorizator:
    build: apps/authorizator
    image: kyoto67/highload/authorizator:latest
    ports:
      - "8877:8080"

  passport:
    build: apps/passport
    image: kyoto67/highload/passport:latest
    ports:
      - "81:81"
    healthcheck:
      test: curl --fail http://passport:81/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  api-gateway:
    build: apps/api-gateway
    image: kyoto67/highload/api-gateway:latest
    ports:
      - "8080:8765"
    healthcheck:
      test: curl --fail http://api-gateway:8765/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  config-server:
    build: service-discovery/config-server
    image: kyoto67/highload/config-server:latest
    ports:
      - "8888:8888"
    environment:
      PATH_TO_CONFIG_DIR: /app/service-discovery/config
      PROFILE: native
    healthcheck:
      test: curl --fail http://config-server:8888/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  eureka-server:
    build: service-discovery/eureka-server
    image: kyoto67/highload/eureka-server:latest
    ports:
      - "8761:8761"
    healthcheck:
      test: curl --fail http://eureka-server:8761/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50