services:
  interviews:
    build: apps/interviewing-service/interviews
    image: highload_systems_proj-interviews:latest

  interviewers:
    build: apps/interviewing-service/interviewers
    image: highload_systems_proj-interviewers:latest

  interview-results:
    build: apps/interviewing-service/interview-results
    image: highload_systems_proj-interview-results:latest

  candidates:
    build: apps/interviewing-service/candidates
    image: highload_systems_proj-candidates:latest

  feedbacks:
    build: apps/interviewing-service/feedbacks
    image: highload_systems_proj-feedbacks:latest

  authorizator:
    build: apps/authorizator
    image: highload_systems_proj-authorizator:latest

  passport:
    build: apps/passport
    image: highload_systems_proj-passport:latest
    ports:
      - "81:81"
    healthcheck:
      test: curl --fail http://passport:81/ping || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  api-gateway:
    build: apps/api-gateway
    image: highload_systems_proj-api-gateway:latest
    ports:
      - "8080:8765"
    healthcheck:
      test: curl --fail http://api-gateway:8765/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  config-server:
    build: service-discovery/config-server
    image: highload_systems_proj-config-server:latest
    ports:
      - "8888:8888"
    environment:
      PATH_TO_CONFIG_DIR: /app/service-discovery/config
      PROFILE: native
    healthcheck:
      test: curl --fail http://config-server:8888/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  eureka-server:
    build: service-discovery/eureka-server
    image: highload_systems_proj-eureka-server:latest
    ports:
      - "8761:8761"
    healthcheck:
      test: curl --fail http://eureka-server:8761/actuator/health || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  interviews-postgres:
    build: ./pg
    image: highload_systems_proj-interviewing-service-postgres:latest
    ports:
      - '5252:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interviewing-service-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  interviewers-postgres:
    build: ./pg
    image: highload_systems_proj-interviewing-service-postgres:latest
    ports:
      - '5253:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interviewing-service-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  interview-results-postgres:
    build: ./pg
    image: highload_systems_proj-interviewing-service-postgres:latest
    ports:
      - '5254:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interviewing-service-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  feedbacks-postgres:
    build: ./pg
    image: highload_systems_proj-interviewing-service-postgres:latest
    ports:
      - '5255:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interviewing-service-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  candidates-postgres:
    build: ./pg
    image: highload_systems_proj-interviewing-service-postgres:latest
    ports:
      - '5256:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=interviewing-service-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  passport-postgres:
    build: ./pg
    image: highload_systems_proj-passport-postgres:latest
    ports:
      - '5251:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=passport-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50

  api-gateway-postgres:
    build: ./pg
    image: highload_systems_proj-api-gateway-postgres:latest
    ports:
      - '5353:5432'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: pwd
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pwd
      POSTGRESQL_PASSWORD_ENCRYPTION: md5
      POSTGRESQL_PGAUDIT_LOG: all, -misc
    healthcheck:
      test: psql 'host=api-gateway-postgres port=5432 user=postgres password=pwd dbname=postgres' -c 'select 1' || exit 1
      start_period: 180s
      timeout: 5s
      interval: 30s
      retries: 50
