include:
  - c-network.yaml

services:
  interviewing-service:
    extends:
      file: c-services.yaml
      service: interviewing-service
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: c-services.yaml
      service: postgres
