include:
  - c-network.yaml

services:

  file-manager:
    extends:
      file: c-services.yaml
      service: file-manager
    depends_on:
      api-gateway:
        condition: service_healthy

  interviews:
    extends:
      file: c-services.yaml
      service: interviews
    depends_on:
      api-gateway:
        condition: service_healthy
      interviews-postgres:
        condition: service_healthy

  interviews-postgres:
    extends:
      file: c-storages.yaml
      service: interviews-postgres

  interviewers:
    extends:
      file: c-services.yaml
      service: interviewers
    depends_on:
      api-gateway:
        condition: service_healthy
      interviewers-postgres:
        condition: service_healthy

  interviewers-postgres:
    extends:
      file: c-storages.yaml
      service: interviewers-postgres

  candidates:
    extends:
      file: c-services.yaml
      service: candidates
    depends_on:
      api-gateway:
        condition: service_healthy
      candidates-postgres:
        condition: service_healthy

  candidates-postgres:
    extends:
      file: c-storages.yaml
      service: candidates-postgres

  feedbacks:
    extends:
      file: c-services.yaml
      service: feedbacks
    depends_on:
      api-gateway:
        condition: service_healthy
      feedbacks-postgres:
        condition: service_healthy

  feedbacks-postgres:
    extends:
      file: c-storages.yaml
      service: feedbacks-postgres

  interview-results:
    extends:
      file: c-services.yaml
      service: interview-results
    depends_on:
      api-gateway:
        condition: service_healthy
      interview-results-postgres:
        condition: service_healthy

  interview-results-postgres:
    extends:
      file: c-storages.yaml
      service: interview-results-postgres

  authorizator:
    extends:
      file: c-services.yaml
      service: authorizator
    depends_on:
      api-gateway:
        condition: service_healthy

  api-gateway:
    extends:
      file: c-services.yaml
      service: api-gateway
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      passport:
        condition: service_healthy
      api-gateway-postgres:
        condition: service_healthy

  eureka-server:
    extends:
      file: c-services.yaml
      service: eureka-server
    depends_on:
      - kafka-ui

  config-server:
    extends:
      file: c-services.yaml
      service: config-server
    depends_on:
      eureka-server:
        condition: service_healthy

  passport:
    extends:
      file: c-services.yaml
      service: passport
    depends_on:
      config-server:
        condition: service_healthy
      passport-postgres:
        condition: service_healthy

  passport-postgres:
    extends:
      file: c-storages.yaml
      service: passport-postgres

  api-gateway-postgres:
    extends:
      file: c-storages.yaml
      service: api-gateway-postgres

  zookeeper:
    extends:
      file: c-kafka.yaml
      service: zookeeper

  kafka1:
    extends:
      file: c-kafka.yaml
      service: kafka1

  kafka2:
    extends:
      file: c-kafka.yaml
      service: kafka2

  kafka3:
    extends:
      file: c-kafka.yaml
      service: kafka3

  kafka-ui:
    extends:
      file: c-kafka.yaml
      service: kafka-ui