apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-interview-results
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-interview-results
  template:
    metadata:
      labels:
        app: postgres-interview-results
    spec:
      containers:
        - name: postgres
          image: kyoto67/highload/interview-results-postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "pwd"
            - name: POSTGRES_USER
              value: "postgres"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-interview-results-storage
      volumes:
        - name: postgres-interview-results-storage
          persistentVolumeClaim:
            claimName: postgres-interview-results-pvc

