apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviewers-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interviewers-postgres
  template:
    metadata:
      labels:
        app: interviewers-postgres 
    spec:
      containers:
        - name: postgres
          image: kyoto67/highload/interviewers-postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "pwd"
            - name: POSTGRES_USER
              value: "postgres"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-interviewers-storage
      volumes:
        - name: postgres-interviewers-storage
          persistentVolumeClaim:
            claimName: postgres-interviewers-pvc

