name: Build and Test Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker tags
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io

      - name: Build and push Docker images
        run: |
          docker build -t kyoto67/highload/base:${{ env.IMAGE_TAG }} .

          images=(
            "api-gateway"
            "authorizator"
            "passport"
            "interviewing-service/candidates"
            "interviewing-service/feedbacks"
            "interviewing-service/interviews"
            "interviewing-service/interviewers"
            "interviewing-service/interview-results"
          )

          for image in "${images[@]}"; do
            docker build --build-arg BASE_IMAGE_VERSION=${{ env.IMAGE_TAG }} -t ghcr.io/kyoto67/highload/$image:${{ env.IMAGE_TAG }} ./apps/$image
            docker push ghcr.io/kyoto67/highload/$image:${{ env.IMAGE_TAG }}
          done

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io

      - name: Run Dockerized tests
        run: |
          images=(
            "api-gateway"
            "authorizator"
            "passport"
            "interviewing-service/candidates"
            "interviewing-service/feedbacks"
            "interviewing-service/interviews"
            "interviewing-service/interviewers"
            "interviewing-service/interview-results"
          )

          for image in "${images[@]}"; do
            docker run --rm ghcr.io/kyoto67/highload/$image:${{ env.IMAGE_TAG }} ./mvnw test
          done

      - name: Archive JaCoCo coverage report
        run: |
          mkdir -p coverage
          cp -r candidates/site/jacoco/ coverage/candidates
          cp -r feedbacks/site/jacoco/ coverage/feedbacks
          cp -r interviews/site/jacoco/ coverage/interviews
          cp -r interviewers/site/jacoco/ coverage/interviewers
          cp -r interview-results/site/jacoco/ coverage/interview-results
          cp -r api-gateway/site/jacoco/ coverage/api-gateway
          cp -r authorizator/site/jacoco/ coverage/authorizator
          cp -r passport/site/jacoco/ coverage/passport

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: coverage